### DISCUSSION TITLE
Environment variables in NuGet.config together with Docker build in Azure Pipelines

### DISCUSSION THREAD

**Discussion by danielhertzman** [dotnet/dotnet-docker#4282] [Q&A]
Hello!

I'm attempting to use Nuget.config to authenticate towards our own artifact feed in Azure DevOps during Docker build job. I follow the instructions given here: https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file#nugetconfig-environment-variable-support

Here is our NuGet.config:
```<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="key" value="https://pkgs.dev.azure.com/<org>/<project>/_packaging/<package>/nuget/v3/index.json" />
  </packageSources>
  <packageSourceCredentials>
    <key>
      <add key="Username" value="%Nuget_CustomFeedUserName%" />
      <add key="ClearTextPassword" value="%Nuget_CustomFeedPassword%" />
    </key>
  </packageSourceCredentials>
</configuration>
```

This is how our Dockerfile looks like:
```
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR ./app
EXPOSE 80
EXPOSE 443

ARG Nuget_CustomFeedUserName
ARG Nuget_CustomFeedPassword

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore --configfile "NuGet.config"

FROM build AS publish
RUN dotnet publish "OurProject.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR ./app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "OurProject.dll"]
```

Here is our Docker build task. Password and UserName variables comes from a variable group and we have verified that we get the values. 
```
- task: Docker@2
    inputs:
      command: 'build'
      Dockerfile: '**/Dockerfile'
      arguments: '--build-arg Nuget_CustomFeedUserName=$(UserName) --build-arg Nuget_CustomFeedPassword=$(Password)'
```

When we run the Docker build task, we get ```Unable to load the service index for source```.

Anyone who maybe knows what we're doing wrong?
