### ISSUE TITLE
Dotnet restore throws `NuGet.Config is not valid XML.  Data at the root level is invalid. Line 1, position 1.

### ISSUE THREAD

**Issue by bdollerup** [dotnet/dotnet-docker#1867]
## Summary
I've got a build task in an Azure DevOps pipeline. It builds two Linux containers (amd64 and arm32) and Windows (amd64) ditto. I've both tasks have run just fine. Recently, I've added a private NuGet feed to my build pipeline and I needed to inject the Nuget file into the build task. With the  `echo Nuget.Config` the Linux container builds work fine but the windows ditto fail.

## Steps to reproduce the issue
1. Dockerfile looks as follows:

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
  WORKDIR /app
  EXPOSE 80
  EXPOSE 443

  FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build

  #Setup args
  ARG ACCESS_TOKEN
  ARG USER
  ARG ARTIFACTS_ENDPOINT
  WORKDIR /src

RUN echo "<?xml version='1.0' encoding='utf-8'?><configuration><packageSources><add key='customfeed' value='$ARTIFACTS_ENDPOINT' /><add key='nuget.org' value='https://api.nuget.org/v3/index.json' /></packageSources><packageSourceCredentials><customfeed><add key='Username' value='xxxx' /><add key='ClearTextPassword' value='$ACCESS_TOKEN' /></customfeed></packageSourceCredentials></configuration>" > NuGet.Config

COPY ["BBDFamilyDashboard4.web.csproj", ""]
RUN dotnet restore "BBDFamilyDashboard4.web.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "BBDFamilyDashboard4.web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BBDFamilyDashboard4.web.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-nanoserver-1809 AS runtime
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BBDFamilyDashboard4.web.dll"]
```

2. the Azure build pipeline (fragment) looks like this:

  
```
- template: azure-pipeline.docker.jobtemplate.yaml
    parameters:
      name: 'nanoserver_1809'  
      os: 'windows'
      architecture: 'amd64'
      vmImage: 'windows-latest'
      buildContext: 'src'
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      containerRegistry: $(dockerRegistryServiceConnection)
      DockerfilePath: '$(Build.SourcesDirectory)/BBDFamilyDashboard4.web/'    
      tag: $(Build.BuildId)
```

with a template like this:

    
```
jobs:  
    - job: ${{ format('{0}_{1}', parameters.os, parameters.architecture) }}
    displayName: Building ${{ format('{0}/{1}', parameters.os, parameters.architecture) }}
    pool:
        vmImage: ${{ parameters.vmImage }}
    variables:
        dockerFileExt: ${{format('{0}-{1}', parameters.os, parameters.architecture) }}   
    steps:
    - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
        command: build
        repository: ${{ parameters.imageRepository }}
        dockerfile: '${{ parameters.dockerfilePath }}/Dockerfile.$(dockerFileExt)'
        containerRegistry: ${{ parameters.dockerRegistryServiceConnection }}
        arguments: '--build-arg ACCESS_TOKEN="$(NUGET_PAT)" --build-arg ARTIFACTS_ENDPOINT="$(ARTIFACTS_ENDPOINT)" --build-arg USER="xxx"'
        tags: |
            ${{format('{0}-{1}-{2}', parameters.os, parameters.architecture, parameters.tag )}}
```

 
3.

## Expected behavior
Docker images to be successfully built.

## Actual behavior

```
C:\Program Files\dotnet\sdk\3.1.201\NuGet.targets(536,5): error : NuGet.Config is not valid XML. Path: 'C:\src\NuGet.Config'. [C:\src\BBDFamilyDashboard4.web.csproj]
C:\Program Files\dotnet\sdk\3.1.201\NuGet.targets(536,5): error :   Data at the root level is invalid. Line 1, position 1. [C:\src\BBDFamilyDashboard4.web.csproj]
The command 'cmd /S /C dotnet restore "BBDFamilyDashboard4.web.csproj"' returned a non-zero code: 1
```

## Output of `docker version`
Version is  2.166.1

```
