### ISSUE TITLE
Provide guidance for using `update-ca-certificates` in distroless images

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#5045]
### Describe the Problem

Our Ubuntu Chiseled images only includes the [ca-certificates_data slice](https://github.com/canonical/chisel-releases/blob/ubuntu-22.04/slices/ca-certificates.yaml), which excludes tools like `update-ca-certificates` in order to reduce image size (this utility isn't typically needed at container runtime). However, if users want to add certificates at container build time, there's no documented way to do so in Ubuntu Chiseled.

### Describe the Solution

There should be a documented way to run the `update-ca-certificates` tool in the image's build layer, and copy the results to the runtime layer.

### Other Information

Context: https://devblogs.microsoft.com/dotnet/announcing-dotnet-chiseled-containers/comment-page-2/#comment-20182

**Comment by lbussell** [comment]
Slightly related: https://github.com/dotnet/dotnet-docker/issues/4997

**Comment by marcmognol** [comment]
Hi @lbussell 

In my company, I do prefer mounting the certificate as a volumeMount instead of integrating it in the container image.

Below an example of my Deployment manifest :
```
          volumeMounts:
          - name: secrets
            subPath: ROOT-CA-CERTIFICATE
            mountPath: /etc/ssl/certs/contoso-ca-certificates.crt
            readOnly: true
```

The certificate is stored in a common keyvault and mounted as a volume in all my deployments. This way, I can update the certificate in the keyvault once, restart all deployments and voilà !

Let me know, if my answer is not clear.
