### ISSUE TITLE
Deprecated Azure pipeline task Docker@0 in documentation/scenarios/nuget-credentials.md

### ISSUE THREAD

**Issue by simpletasks** [dotnet/dotnet-docker#5086]
In documentation/scenarios/nuget-credentials.md under Azure Pipelines, in code snippet:
```yaml 
    steps:
    - task: NuGetAuthenticate@1
      displayName: 'Authenticate to NuGet'

    - task: Docker@0
      displayName: 'build container'
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'
        buildArguments: |
          FEED_ACCESSTOKEN=$(VSS_NUGET_ACCESSTOKEN)
```
Docker@0 should be replaced with Docker@2
