### ISSUE TITLE
K8s deployment file `hello-dotnet.yaml` is malformed

### ISSUE THREAD

**Issue by danielemarostica** [dotnet/dotnet-docker#5214]
### Describe the Bug

Hello, I got the following error whenever i run the kubectl apply command specified in `README.md` file

Deployment in version "v1" cannot be handled as a Deployment: strict decoding error: unknown field "spec.template.metadata.containers", unknown field "spec.template.metadata.volumes"

### Steps to Reproduce

Just run:
$ kubectl apply -f https://raw.githubusercontent.com/dotnet/dotnet-docker/main/samples/kubernetes/hello-dotnet/hello-dotnet.yaml

### Other Information

I noticed that `samples/kubernetes/hello-dotnet/hello-dotnet.yaml` file is malformed as `containers` field should be declared inside `template/spec` field. Currently it's defined under `template/metadata` one.

expected:
```yaml
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aspnetapp
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      containers:
      - name: aspnetapp
      - ...
```

actual:
```yaml
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aspnetapp
  template:
    metadata:
      labels:
        app: aspnetapp
      containers:
      - name: aspnetapp
      - ...
```
