### ISSUE TITLE
Maestro's code is causing CG alerts in all dotnet docker pipelines

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#5332]
### Describe the Bug

Because we reference the https://github.com/dotnet/versions repo in our builds, dotnet-docker-nightly is getting CG alerts for source code in that repo (from the Maestro service).

### Proposed solution

We can ignore unused directories from the dotnet/versions repo in SDL scanning (across all of our pipelines) with the syntax ([from 1ES documentation](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sdlanalysis/componentgovernance), internal link):

```yaml
extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      componentgovernance:
        ignoreDirectories: $(Build.SourcesDirectory)/test
        alertWarningLevel: Medium
        failOnAlert: true
        verbosity: Normal
```
