### ISSUE TITLE
Static Analysis Tests for Tag Validation

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/dotnet-docker#5838]
### Problem to solve

We need to implement static tests (based on image-builder manifest/README) for the following scenarios to ensure the correctness of our tag schema and adherence to our tagging rules:

**Tag Schema Validation**
- Ensure the tag schema matches the description in [supported-tags.md](https://github.com/dotnet/dotnet-docker/blob/main/documentation/supported-tags.md). Specifically:
   - Verify that the Alpine floating tag references the correct version of Alpine.
   - Confirm that appliance images use the correct tags, as they follow a different schema.

**"Latest" Tag Rules**
-  https://github.com/dotnet/dotnet-docker/pull/5852
- Ensure the following rules are adhered to for the latest tags:
  - There is only one latest tag per repository.
  - The latest tag points to the expected version:
      - For main, it should point to the latest non-preview/release candidate major release.
      - For nightly, it should point to the latest unreleased version.

### Additional implementation details
My initial thoughts are that we should use the tag tables/READMEs for this validation. Upon initial examination of this issue, parsing the manifest is difficult as it requires deserialization and replacement of variables. This is something that is already handled by the image builder, and rewriting this logic is tedious and prevents us from making changes to the manifest without large pieces of the test code becoming invalid. Since we already validate the readmes against the manifest, the readmes are another truthful place to validate tags that doesn't require immense parsing and duplicate image-builder logic. That said, another option for these tests, other than the manifest and the readme, is to make the image builder output some sort of artifact that contains the values we wish to validate.

**Comment by lbussell** [comment]
@mthalman @ellahathaway I do like the idea of an imagebuilder command that resolves all the variable values in the manifest. However that still means we'd need to parse the manifest. Parsing the manifest would be useful for other reasons such as https://github.com/dotnet/dotnet-docker/issues/5337.

Another option could be to re-use the MCR tags metadata yaml that we already generate. That would prevent needing to read the manifest from the dotnet-docker repo. However we'd still be stuck parsing another new file format from this repo, just yaml this time instead of json.

This would require a new command to output the tags metadata files to the disk, and would also require an option to include undocumented tags in the output.

Example:
```yaml
  - tags: [ 9.0.0-preview.7-bookworm-slim-amd64, 9.0-preview-bookworm-slim-amd64, 9.0.0-preview.7-bookworm-slim, 9.0-preview-bookworm-slim, 9.0.0-preview.7, 9.0-preview ]
    architecture: amd64
    os: linux
    osVersion: Debian 12
    dockerfile: https://github.com/dotnet/dotnet-docker/blob/e48d296ed821d3bf00cf90f26ddc236077a8c610/src/runtime/9.0/bookworm-slim/amd64/Dockerfile
    customSubTableTitle: .NET 9 Preview Tags
```
